config/routes.rb
Green::Application.routes.draw do
  root :to => 'recipes#index'
  devise_for :admins
  devise_for :users
  match ':controller/ujs/:action'
  match ':controller/:id/ujs/:action'
  resources :recipes
  resources :parts
  resources :ingredients

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :recipe
  validates_presence_of :posting 
  validates_presence_of :rank
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :user
  has_many :parts
  has_many :recipes, :through => :parts
  accepts_nested_attributes_for :parts
  validates_presence_of :name, :variety
  validates_inclusion_of :variety, :in =>["Green", "Fruit", "Vegetable", "Other"]
end

app/models/part.rb
class Part < ActiveRecord::Base
  validates_presence_of :amount, :ingredient_id
  belongs_to  :recipe
  belongs_to  :ingredient
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :user
  has_many :comments, :dependent=>:destroy
  has_many :parts, :dependent=>:destroy
  accepts_nested_attributes_for :parts, :reject_if => :all_blank
  has_many :ingredients, :through=>:parts
  validates_presence_of :name#, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :ingredients
  has_many :recipes
  has_many :comments, :dependent=>:destroy
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  # GET /ingredients
  # GET /ingredients.xml
  before_filter :authenticate_user!, :except=> [:index, :show]
  def index
    @ingredients = Ingredient.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /ingredients/1
  # GET /ingredients/1.xml
  def show
    @ingredient = Ingredient.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /ingredients/new
  # GET /ingredients/new.xml
  def new
    @ingredient = Ingredient.new
    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /ingredients/1/edit
  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  # POST /ingredients
  # POST /ingredients.xml
  def create
    @ingredient = Ingredient.new(params[:ingredient])
    @ingredient.user_id = current_user.id
    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to(@ingredient, :notice => 'Ingredient was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /ingredients/1
  # PUT /ingredients/1.xml
  def update
    @ingredient = Ingredient.find(params[:id])

    respond_to do |format|
      if @ingredient.update_attributes(params[:ingredient])
        format.html { redirect_to(@ingredient, :notice => 'Ingredient was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @ingredient.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.xml
  def destroy
    @ingredient = Ingredient.find(params[:id])
    @ingredient.destroy

    respond_to do |format|
      format.html { redirect_to(ingredients_url) }
      format.xml  { head :ok }
    end
  end
end
#adding a comment to test

app/controllers/parts_controller.rb
class PartsController < ApplicationController
   before_filter :authenticate_user!, :except=> [:index, :show]
  # GET /parts
  # GET /parts.xml
  def index
    @parts = Part.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @parts }
    end
  end

  # GET /parts/1
  # GET /parts/1.xml
  def show
    @part = Part.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @part }
    end
  end

  # GET /parts/new
  # GET /parts/new.xml
  def new
    @part = Part.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @part }
    end
  end

  # GET /parts/1/edit
  def edit
    @part = Part.find(params[:id])
  end

  # POST /parts
  # POST /parts.xml
  def create
    @part = Part.new(params[:part])

    respond_to do |format|
      if @part.save
        format.html { redirect_to(@part, :notice => 'Part was successfully created.') }
        format.xml  { render :xml => @part, :status => :created, :location => @part }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @part.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /parts/1
  # PUT /parts/1.xml
  def update
    @part = Part.find(params[:id])

    respond_to do |format|
      if @part.update_attributes(params[:part])
        format.html { redirect_to(@part, :notice => 'Part was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @part.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /parts/1
  # DELETE /parts/1.xml
  def destroy
    @part = Part.find(params[:id])
    @part.destroy

    respond_to do |format|
      format.html { redirect_to(parts_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
   before_filter :authenticate_user!, :except=> [:index, :show] 
  # GET /recipes
  # GET /recipes.xml
  def index
    @recipes = Recipe.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end
  
  def addPart
  end
  
  
  # GET /recipes/1
  # GET /recipes/1.xml
  def show
    @recipe = Recipe.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /recipes/new
  # GET /recipes/new.xml
  def new
    @recipe = Recipe.new
    2.times{@recipe.parts.build}
    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /recipes/1/edit
  def edit
    @recipe = Recipe.find(params[:id])
  end

  # POST /recipes
  # POST /recipes.xml
  def create
    @recipe = Recipe.new(params[:recipe])
    @parts = @recipe.parts
    respond_to do |format|
      if @recipe.save
        format.html { redirect_to(@recipe, :notice => 'Recipe was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /recipes/1
  # PUT /recipes/1.xml
  def update
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      if @recipe.update_attributes(params[:recipe])
        format.html { redirect_to @recipe, :notice => 'Recipe was successfully updated.' }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.xml
  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to(recipes_url) }
    end
  end
  
  def add_part
    @part = Part.new
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/ingredients/_form.html.erb
<%= simple_form_for(@ingredient) do |f| %>
  <% if @ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% @ingredient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="inputs">
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/ingredients/_form.html.haml
= simple_form_for @ingredient do |f|
  = f.input :name, :label => "Ingredient Name"
  = f.input :variety, :collection => ["Green", "Fruit", "Vegetable", "Other"]
  = f.button :submit

app/views/ingredients/edit.html.erb
<h1>Editing ingredient</h1>

<%= render 'form' %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/index.html.erb
<h1>Listing ingredients</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ingredients.each do |ingredient| %>
  <tr>
    <td><%= link_to 'Show', ingredient %></td>
    <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
    <td><%= link_to 'Destroy', ingredient, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ingredient', new_ingredient_path %>

app/views/ingredients/index.html.haml
%h1 Listing ingredients

%table{:border => 1}
  %tr
    %th Ingredient Name
    %th Variety
    %th Who added it
    %th User Id

  - @ingredients.each do |i|
    %tr
      %td
        = i.name
      %td
        = i.variety
      %td
        = i.user.email
      %td
        = i.user.id

= link_to 'New Ingredient', new_ingredient_path

app/views/ingredients/new.html.erb
<h1>New ingredient</h1>

<%= render 'form' %>

<%= link_to 'Back', ingredients_path %>

app/views/ingredients/new.html.haml
%h1 New ingredient
= render 'form'

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
<%= link_to 'Back', ingredients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Green</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    = csrf_meta_tag 
    %title Green Smoothies
  %body
    = javascript_include_tag :defaults
    %ul
      = render 'devise/login_items'
      = render 'devise/registration_items'
    %p 
      .notice
        = notice 
    %p 
      .alert
        = alert 
  = yield

app/views/parts/_form.html.erb
<%= simple_form_for(@part) do |f| %>
  <% if @part.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@part.errors.count, "error") %> prohibited this part from being saved:</h2>

      <ul>
      <% @part.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="inputs">
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/parts/_form.html.haml
= form_tag('addPart') do
  = select_tag ('Amount', "<option>1</option>")
  = submit_tag("Add Ingredient")

app/views/parts/edit.html.erb
<h1>Editing part</h1>

<%= render 'form' %>

<%= link_to 'Show', @part %> |
<%= link_to 'Back', parts_path %>

app/views/parts/index.html.erb
<h1>Listing parts</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @parts.each do |part| %>
  <tr>
    <td><%= link_to 'Show', part %></td>
    <td><%= link_to 'Edit', edit_part_path(part) %></td>
    <td><%= link_to 'Destroy', part, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Part', new_part_path %>

app/views/parts/new.html.erb
<h1>New part</h1>

<%= render 'form' %>

<%= link_to 'Back', parts_path %>

app/views/parts/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_part_path(@part) %> |
<%= link_to 'Back', parts_path %>

app/views/recipes/_addPartForm.html.haml
= for @recipe.parts.size do |p|
  = p.amount

app/views/recipes/_form.html.erb
<%= simple_form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="inputs">
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/recipes/_form.html.haml
- form_for @recipe do |f|
  = f.label :name, 'Name:'
  = f.text_field :name
  %table#INGREDIENTS
    = f.fields_for :parts do |p|
      %tr
        %td
          = p.label :amount
          = p.select "amount", {1=>1, 2=>2, 3=>3, 4=>4, 5=>5, 6=>6, 7=>7, 8=>8, 9=>9, 10=>10}, { :include_blank => true }
        %td
          = p.label :ingredient
          = p.collection_select :ingredient_id, Ingredient.all, :id, :name, { :include_blank => true }
  = link_to "Add Another Ingredient", "ujs/add_part", :remote=>true
  = f.submit :submit

app/views/recipes/_newpart.html.haml
= fields_for @part do |p|
  %tr
    %td
      = p.label :amount
      = p.select "amount", {1=>1, 2=>2, 3=>3, 4=>4, 5=>5, 6=>6, 7=>7, 8=>8, 9=>9, 10=>10}, { :include_blank => true }
    %td
      = p.label :ingredient
      = p.collection_select :ingredient_id, Ingredient.all, :id, :name , { :include_blank => true }

app/views/recipes/_part.html.haml
%part
  - new_or_exisiting = part.new_record? ? 'new': 'existing'
  - prefix = "project[#{new_or_existing}_task_attributes][]"
  - fields_for prefix, part do |part_form|
    Amount:
    = part_form.text_field :amount

app/views/recipes/add_part.js.erb
$('#INGREDIENTS > tbody > tr').last().after("<%= escape_javascript(render(:partial => 'newpart')) %>")

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/edit.html.haml
%h1 New recipe Sucka!!

= render 'form'

= link_to 'Create New Ingredient', new_ingredient_path
|
= link_to 'Show', @recipe
|
= link_to 'Back', recipes_path

app/views/recipes/index.html.erb
<h1>Listing recipes</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @recipes.each do |recipe| %>
  <tr>
    <td><%= link_to 'Show', recipe %></td>
    <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
    <td><%= link_to 'Destroy', recipe, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/index.html.haml
#LocalTitle
  All Recipes
  
%table#RecipeListing
  %tr
    %th
      Name
    %th
      Description
    %th
      Rating
    %th
    %th
    %th    
  - @recipes.each do |r| 
    %tr
      %td
        = r.name
      %td
        THIS WILL BE DESCRIPTION
      %td
        THIS WILL BE RATING
      %td
        = link_to 'Show', r
      %td
        = link_to 'Edit', edit_recipe_path(r)
      %td
        = link_to 'Destroy', r, :confirm => 'Are you sure?', :method => :delete 
%br
= link_to 'New Recipe', new_recipe_path

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/new.html.haml
%h1 New recipe Sucka!!

= render 'form'

= link_to 'Back', recipes_path

= link_to 'Create New Ingredient', new_ingredient_path

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.haml
%p#notice  
  = @notice 
%h1
  = @recipe.name
%table  
  - for p in @recipe.parts
    %tr
      %td
        = p.amount
      %td  
        = p.ingredient.name

= link_to 'Edit', edit_recipe_path(@recipe) 
| 
= link_to 'Back', recipes_path